name: Test Custom Email Checker

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]
  push:
    branches: [master, main, 'releases/*', 'backport/*']

jobs:
  verify-email:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Check committer email
        uses: ./.github/actions
        with:
          email_domain: '@wazuh.com,@users.noreply.github.com'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          error_on_fail: 'true'
