name: Test Custom Email Checker

on:
  push:
    branches: [main]

jobs:
  verify-email:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check committer email
        uses: ./.
        with:
          email_domain: '@wazuh.com,@users.noreply.github.com'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          error_on_fail: 'true'
